# PCA on Breast Cancer Dataset

### Here the difference in speed and accuracy is demonstrated between applying PCA and not applying PCA

In [8]:
from sklearn import decomposition,linear_model, datasets
import numpy as np
import time
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [9]:
breast_cancer = datasets.load_breast_cancer()

In [10]:
X = breast_cancer.data
X.shape

(569, 30)

In [11]:
sc = StandardScaler()
X_std = sc.fit_transform(X)
X_std

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [12]:
x_train,x_test,y_train,y_test = train_test_split(X_std,breast_cancer.target,random_state=0)

In [13]:
pca = decomposition.PCA()
pca.fit_transform(x_train)

array([[-2.83807710e+00, -3.19380204e-01, -5.09786956e-01, ...,
         2.21524204e-03,  1.76560105e-02,  2.17290491e-03],
       [-3.23881077e+00,  9.46695152e-01,  1.46301470e+00, ...,
        -3.50930341e-03,  1.56914143e-02,  1.44518116e-02],
       [ 3.92831902e+00, -3.30091570e+00,  1.84183164e+00, ...,
         2.00501871e-02, -3.44990391e-02, -1.16657352e-02],
       ...,
       [-3.17962251e+00,  4.33267733e-01,  5.77005027e-01, ...,
         3.85704447e-02, -4.18716728e-02,  1.59435183e-02],
       [-5.59141525e+00, -7.52889177e-01,  4.06478207e+00, ...,
         1.97618354e-02, -1.70355933e-02,  4.38111630e-03],
       [-1.20802261e+00,  1.32965049e+00,  1.26115052e+00, ...,
        -1.32544095e-02, -1.58653526e-03, -1.14601436e-02]])

In [14]:
pca.explained_variance_

array([1.30274684e+01, 5.81556555e+00, 2.85848795e+00, 1.91901713e+00,
       1.70021491e+00, 1.20663908e+00, 6.53337152e-01, 4.26738474e-01,
       4.26450541e-01, 3.45589858e-01, 3.08054910e-01, 2.56054468e-01,
       2.28152003e-01, 1.43262745e-01, 9.26283031e-02, 7.80260477e-02,
       6.13812037e-02, 5.26182531e-02, 4.50933578e-02, 3.08275366e-02,
       3.03277956e-02, 2.51390631e-02, 2.12226717e-02, 1.77427715e-02,
       1.63886382e-02, 7.83681541e-03, 6.61084728e-03, 1.45257891e-03,
       7.98794510e-04, 1.11908784e-04])

In [15]:
total = sum(pca.explained_variance_)
k = 0
current_variance = 0
while current_variance/total < 0.99:
    current_variance += pca.explained_variance_[k]
    k=k+1
k

17

In [16]:
pca = decomposition.PCA(n_components=17)
x_train_pca = pca.fit_transform(x_train)
x_test_pca = pca.transform(x_test)

In [19]:
#Applying Logistic Regression Without PCA
lr = linear_model.LogisticRegression()
start = time.time()
lr.fit(x_train,y_train)
ending = time.time()
print("Time Taken: ",ending-start)
print(lr.score(x_test,y_test))

Time Taken:  0.03748035430908203
0.965034965034965


In [20]:
#Applying LR with PCA
#Accuracy drops little bit but spead improves drastically by using PCA
lr = linear_model.LogisticRegression()
start = time.time()
lr.fit(x_train_pca,y_train)
ending = time.time()
print("Time Taken: ",ending-start)
print(lr.score(x_test_pca,y_test))

Time Taken:  0.02689814567565918
0.958041958041958
